spring.application.name=petInsurance
server.port=8081


spring.data.mongodb.uri=mongodb+srv://biradarsameer2:iHfd4AlddoZdaFPf@cluster0.k79jdvj.mongodb.net/pet_insurance_db?retryWrites=true&w=majority&appName=Cluster0



# Eureka client properties
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka